### ISSUE TITLE
kRPC Compatibility?

### ISSUE THREAD

**Issue by pbeart** [linuxgurugamer/DangIt#13]
kRPC compatibility would be very useful: it would allow external UIs to be built showing part failure modes etc, and allow those running mission control scenarios a more realistic way to interact with the mod. I have no experience at all with C, but hopefully it wouldn't be too difficult to implement compatibility using the kRPC Service API, and would be very much appreciated.

**Comment by linuxgurugamer** [comment]
If someone were to do this and submit a PR, I'd be happy to accept, but I don't have the time or the desire to do this, sorry
