### ISSUE TITLE
localization BUG

### ISSUE THREAD

**Issue by gnbo** [linuxgurugamer/DangIt#16]
If you use other languages in KSP (e.g. German) some variables will be translated. So also "experienceTrait.TypeName". That's why every time I try to repair something, an error is thrown.

To fix the error you have to change the name of the variable in DangIt/blob/master/DangIt/Failure_modules/FailureModule.cs in line 820 from "kerbal.experienceTrait.TypeName" to   "kerbal.experienceTrait.Config.Name".

See also: https://forum.kerbalspaceprogram.com/index.php?/topic/183531-psa-experiencetraittitle-and-experiencetraittypename-are-both-localized-do-not-use-in-logic-persistence/

**Comment by linuxgurugamer** [comment]
Thank you, I'll push out a release right away
