### ISSUE TITLE
[question]

### ISSUE THREAD

**Issue by CmdrNorthpaw** [linuxgurugamer/DangIt#17]
Is a 1.7.3 update coming any time soon? CKAN won't let me install it without.
Also I appologize for the title.

**Comment by linuxgurugamer** [comment]
It works, follow these instructions to install:

1. Open CKAN
2. Click the menu Settings-> Compatible KSP versions
3. Click the top checkbox labeled 1.7
4. Click the Accept button

It was rebuilt for 1.7.2, and no need to rebuild for 1.7.3.  These instructions will allow CKAN to install any mod compatible with 1.7.0, 1.7.1, 1.7.3 or 1.7.3 into your game
