### ISSUE TITLE
Relative high prices for Spare Parts containers

### ISSUE THREAD

**Issue by Schmitt-Florian** [linuxgurugamer/DangIt#18]
Problem: 
Parts with the ability to contain spare are cost up to 30times more than the same stock parts. 
Eg. the Service Bay (1.25m) costs 9950$ compared to stock 500$. This seems extraordinary high considering you might not even want to store spare parts on some vessels.

Cause:
This seems to be the result of changes made in the SpareParts.cfg which besides adding the ability to store spare parts, increases the cost of the container.

Solution:
I suggest to lower the additional costs for the containers to be more inline with current stock balancing and cost per unit of storage in the "DangIt Repair Bay" part

**Comment by Schmitt-Florian** [comment]
Although the costs per unit of storage are inline with storage in the DangIt Repair Bay after #19, the total cost can still range from 1.7 to 7.5times more than the stock part, which while acceptable seems a bit high in the latter case.

Note: This range tends only to apply to cargo bay parts and the "Mk1FuselageStructural", as crewed parts are balanced against their crew capacity.

---

I don't know if there is a way to calculate the additional cost and storage capacity for cargo bays based of stock part cost, rather than assigning fixed values.

If there is, something like:
`newCost+=stockCost*x`
and
`storageCapacity=(stockCost*x)/14`
would keep the additional cost at 14$ per unit of storage and the added storage capacity inline with the crewed modules.

Multiplier x=0.83 (averaged over all stock and dlc crewed parts) would have the advantage that the same formular could be used to determine cost and storage capacity for crewed parts without changing the balancing, but leave cargo bays at a relative small capacity, due to their little cost (30-88 spare parts for all but the biggest part)

Multiplier x=2, which I would recommend, retaining a somewhat higher capacity at a reasonable price tag (71-214 spare parts for all but the biggest part), but loosing the ability to use the same formular for crewed parts, as their price increaces significantly with crew capacity and this would result in quite high amounts of storage capacity compared to current settings

Edit: did math

**Comment by linuxgurugamer** [comment]
That usually is the cost of the container and all the contained spare parts.  Please check to see if the spare parts container is full, and if it is,empty it out and see how much it consts

**Comment by Genhis** [comment]
@linuxgurugamer Empty container costs 8060 which is 16x higher than the stock cost.
