### ISSUE TITLE
No mute option available

### ISSUE THREAD

**Issue by Davidj361** [linuxgurugamer/DangIt#8]
I don't have an option in the context menu to mute an alarm for a part if it's broken, didn't show for a broken stock battery or a broken stock light.

Here is my mod list: https://pastebin.com/pYQB8HTm

**Comment by linuxgurugamer** [comment]
I need to see the log file as well, as I stated on the forums

**Comment by linuxgurugamer** [comment]
Fixed in 0.7.18.0
