### ISSUE TITLE
ModuleManager 3.0.1 error in Tanks.cfg

### ISSUE THREAD

**Issue by EnterTheNameHere** [linuxgurugamer/DangIt#9]
ModuleManager version 3 indicates error in GameData/DangIt/ModuleManager/Tanks.cfg

Error message:
`[ERR 22:45:15.321] [ModuleManager] Error - more than one pass specifier on a node: DangIt/ModuleManager/Tanks/@PART[*]:HAS[@RESOURCE[*],~name[PotatoRoid],!MODULE[NoFailureModules]]:FOR[DangIt]:FIRST`

(see line 16920 in full log - [KSP.log](https://gist.githubusercontent.com/EnterTheNameHere/6902bb331e4e8952ce13e0f125351f38/raw/ed7fd886673ac7aeba4ed3b53bdfff596d1bcd64/KSP.log); [mods.ckan](https://gist.githubusercontent.com/EnterTheNameHere/6902bb331e4e8952ce13e0f125351f38/raw/ed7fd886673ac7aeba4ed3b53bdfff596d1bcd64/mods.ckan) )

**Comment by linuxgurugamer** [comment]
Fixed in the release, about 5  minutes ago
